classDiagram

class プリント {
  <<entity>>
  プリントID
  元教材参照
  固定レイアウト
  プリント問題一覧
  作成日時
}

class プリント問題 {
  <<entity>>
  プリント問題ID
  元問題参照
  固定出題
  固定解答
  固定解説一覧
  作成日時
}

プリント --> プリント問題
