classDiagram

class 到達目標 {
  <<entity>>
  到達目標ID
  本文
  学年参照
  学習期間参照
  基準タグ一覧
}

class 学年参照 {
  <<value>>
  学年ID
}

class 学習期間参照 {
  <<value>>
  学習期間ID
}

class 基準タグ {
  <<value>>
  キー
  値
}

到達目標 --> 学年参照
到達目標 --> 学習期間参照
到達目標 --> 基準タグ
