%% 問題.mmd
%% 同一行内のコメントアウトは認識されません
%% （）は使用禁止

classDiagram

class 問題 {
  <<entity>>
  問題ID
  非推奨
}

class 出題 {
  <<value>>
  構成要素一覧
}

class 解答 {
  <<value>>
  構成要素一覧
}

class 解説 {
  <<value>>
  構成要素一覧
}

class 構成要素 {
  <<entity>>
  構成要素ID
}

class テキスト要素 {
  <<entity>>
  構成要素ID
  本文
}

class 画像要素 {
  <<entity>>
  構成要素ID
}

class 画像要素アップロード {
  <<entity>>
  構成要素ID
  画像参照
}

class 画像要素生成 {
  <<entity>>
  構成要素ID
  生成方式
  P5スクリプト
}

class 生成方式 {
  <<enum>>
  p5
}

class 画像参照 {
  <<value>>
  アセットID
  MIME種別
  内容ハッシュ
}

class P5スクリプト {
  <<value>>
  言語
  コード
}

class 教材情報参照 {
  <<value>>
  教材情報ID
}

class 到達目標参照 {
  <<value>>
  到達目標ID
}

問題 --> 出題
問題 --> 解答
問題 --> 解説
問題 --> 教材情報参照
問題 --> 到達目標参照

出題 --> 構成要素
解答 --> 構成要素
解説 --> 構成要素

構成要素 <|-- テキスト要素
構成要素 <|-- 画像要素
画像要素 <|-- 画像要素アップロード
画像要素 <|-- 画像要素生成

画像要素アップロード --> 画像参照
画像要素生成 --> 生成方式
画像要素生成 --> P5スクリプト
