classDiagram

class 学習基準 {
  <<entity>>
  学習基準ID
  制定主体参照
  教科一覧
}

class 教科 {
  <<entity>>
  教科ID
  教科名
  分野一覧
}

class 分野 {
  <<entity>>
  分野ID
  分野名
  到達目標参照一覧
}

class 到達目標参照 {
  <<value>>
  到達目標ID
}

class 制定主体参照 {
  <<value>>
  制定主体ID
}

学習基準 --> 制定主体参照
学習基準 --> 教科
教科 --> 分野
分野 --> 到達目標参照
