%% 教材.mmd
%% 同一行内のコメントアウトは認識されません
%% （）は使用禁止

classDiagram

class 教材 {
  <<entity>>
  教材ID
  問題参照一覧
  レイアウト参照
  単元参照
}

class 問題参照 {
  <<value>>
  問題ID
}

class レイアウト参照 {
  <<value>>
  レイアウトID
}

class 単元参照 {
  <<value>>
  単元ID
}

class 単元 {
  <<entity>>
  単元ID
  単元名
  問題順序
}

class 教材テンプレート {
  <<entity>>
  教材テンプレートID
  名称
  レイアウト参照
}

教材 --> 問題参照
教材 --> レイアウト参照
教材 --> 単元参照

単元 --> 問題参照
教材テンプレート --> レイアウト参照
