%% 教材情報.mmd
%% 同一行内のコメントアウトは認識されません
%% （）は使用禁止

classDiagram

class 教材情報 {
  <<value>>
  教材情報ID
  作成区分
  権利情報
}

class 作成区分 {
  <<enum>>
  自作
  出典あり
  不明
}

class 権利情報 {
  <<value>>
  商用利用可否
  再配布可否
  改変可否
}

class 可否 {
  <<enum>>
  許可
  不許可
  不明
}

教材情報 --> 作成区分
教材情報 --> 権利情報

権利情報 --> 可否
